version: '3'

networks:
  prodnetwork:
    driver: bridge

volumes:
  jenkins-data:
  
services:
  jenkins:
    image: "jenkins/jenkins:lts"
    restart: always
    ports:
      - "18080:8080"
    networks:
      - prodnetwork
    volumes:
      - jenkins-data:/var/lib/jenkins/
    depends_on:
      - sonar
    environment:
      - SONAR_PORT=9000
      - SONAR_DB_PORT=5432

  sonardb:
    networks:
      - prodnetwork
    restart: always
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar

  sonar:
    image: "sonarqube:latest"
    restart: always
    ports:
     - "19000:9000"
     - "19092:9092"
    networks:
      - prodnetwork
    depends_on:
      - sonardb
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONARQUBE_JDBC_PASSWORD=sonar

  gitlab:
    image: "gitlab/gitlab-ce:latest"
    restart: always
    networks:
      - prodnetwork
    ports:
      - "10080:80"
      - "10443:443"
      - "10022:22"
    volumes:
      - /opt/gitlab/config:/etc/gitlab
      - /opt/gitlab/logs:/var/log/gitlab
      - /opt/gitlab/data:/var/opt/gitlab